In [485]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import cross_val_score
from  sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import classification_report
from sklearn.ensemble import VotingClassifier, BaggingClassifier, RandomForestClassifier

In [486]:
df = pd.read_csv("../datasets/winequality-red.csv")

In [487]:
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5

In [488]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [489]:
df = df.sample(frac=1)

In [490]:
X, y = df.drop("quality", axis=1),  df["quality"]

In [491]:
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.metrics import mean_squared_error

In [492]:
X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8)

In [493]:
model = ExtraTreesRegressor(max_depth=20, max_features=9)

In [494]:
model.fit(X_train, y_train)

ExtraTreesRegressor(max_depth=20, max_features=9)

In [495]:
predicted = model.predict(X_test)
train_predicted = model.predict(X_train)
train_mse = mean_squared_error(y_train, train_predicted)
mse = mean_squared_error(y_test, predicted)
rmse = np.sqrt(mse)
train_rmse = np.sqrt(train_mse)
print(train_rmse, rmse)

0.0231323323164608 0.5482846681038047

In [496]:
def displayscores(scores):
    print("Scores: ", scores)
    print("Mean: ", scores.mean())
    print("Standard deviation: ", scores.std())

In [497]:
scores = cross_val_score(model, X, y, scoring="neg_mean_squared_error", n_jobs = -1, cv=10)
displayscores(np.sqrt(-scores))

Scores:  [0.4802124  0.62434231 0.53292364 0.58894669 0.5479757  0.55456919
 0.53407628 0.61914011 0.59243158 0.52632152]
Mean:  0.5600939420620212
Standard deviation:  0.04313544004090919